# Generated by Django 4.1.3 on 2022-11-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('able_to_modify', models.BooleanField(default=False, null=True)),
                ('able_to_edit', models.BooleanField(default=False, null=True)),
                ('able_to_create', models.BooleanField(default=False, null=True)),
                ('able_to_delete', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('biography', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=1000, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('show_biography', models.BooleanField(default=True, null=True)),
                ('show_contact', models.BooleanField(default=True, null=True)),
                ('show_creations', models.BooleanField(default=True, null=True)),
                ('show_members', models.BooleanField(default=False, null=True)),
                ('members', models.ManyToManyField(through='organisation.Membership', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
