# Generated by Django 4.1.3 on 2022-11-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphenotype',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male/Female'), (2, 'Male'), (3, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male/Female'), (2, 'Male'), (3, 'Female')], default=1),
        ),
    ]
