# Generated by Django 4.1.3 on 2022-11-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypes', '0002_alter_historicalphenotype_sex_alter_phenotype_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenotype',
            options={'ordering': ('name',), 'permissions': (('can_approve', 'Can approve phenotype'),)},
        ),
    ]
