# Generated by Django 4.1.3 on 2022-11-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phenotypes', '0001_initial'),
        ('concepts', '0001_initial'),
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='created_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_phenotype', to='phenotypes.phenotype'),
        ),
        migrations.AddField(
            model_name='component',
            name='codes',
            field=models.ManyToManyField(blank=True, related_name='related_codes', through='concepts.CodeRule', to='codelist.code'),
        ),
        migrations.AddField(
            model_name='coderule',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.code'),
        ),
        migrations.AddField(
            model_name='coderule',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.component'),
        ),
    ]
