# Generated by Django 4.1.3 on 2022-11-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='status',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalconcept',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='historicalconcept',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalconcept',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='historicalconcept',
            name='updated_by',
        ),
    ]
