# Generated by Django 4.1.3 on 2022-11-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_remove_concept_brand_remove_concept_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalConcept',
        ),
    ]
