# Generated by Django 4.1.3 on 2022-11-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypes', '0003_alter_phenotype_options'),
        ('concepts', '0003_delete_historicalconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='created_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_phenotype', to='phenotypes.phenotype'),
        ),
    ]
