# Generated by Django 4.1.3 on 2022-11-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CodingSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CodeList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codes', models.ManyToManyField(blank=True, related_name='codelist', to='codelist.code')),
                ('coding_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_coding_system', to='codelist.codingsystem')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='code',
            name='coding_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coded', to='codelist.codingsystem'),
        ),
    ]
